---

- hosts: all
  become: true
  tasks:

  - name: Copy file with custom prompt to managed host
    ansible.builtin.copy:
      src: ./.bash_prompt
      dest: "~"
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'

  - name: Modify PS1 variable
    blockinfile:
      state: present
      insertafter: EOF
      dest: "~/.bashrc"
      content: "source ~/.bash_prompt"
        